# Generated by Django 4.2.5 on 2024-01-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20240108_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_expense',
            name='vendor_balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasedebit',
            name='vendor_balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='vendor_balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurring_bill',
            name='vendor_balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='vendor_balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='vendor_balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
