# Generated by Django 4.2.5 on 2024-01-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_purchase_expense_vendor_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='openingbalance',
            field=models.IntegerField(null=True),
        ),
    ]
